[tool.poetry]
name = "crash-dedup"
version = "0.1.0"
description = "Deduplication of program crashes enforced by sanitizes"
authors = ["XXX <XXX>"]
# readme = "README.md"
packages = [{include = "cdd", from = "src"}]

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.9.0"
pyyaml = "^6.0.1"
types-pyyaml = "^6.0.12.11"

[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
black = "^24.3.0"
mypy = "^1.5.1"
bandit = "^1.7.5"
pytest = "^7.4.2"

[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = ["tests"]

[tool.coverage.run]
branch = true
command_line = "-m pytest"

[tool.coverage.report]
show_missing = true
# fail_under = 80

[tool.poetry.scripts]
cdd = "cdd.main:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
